repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: ^report/
      - id: black-jupyter
        exclude: ^report/
  - repo: https://gitlab.com/iamlikeme/nbhooks
    rev: 1.0.0  # Set to the most recent version
    hooks:
    - id: nb-ensure-clean
